### ISSUE TITLE
Feature Request: Uninstall function or similar support

### ISSUE THREAD

**Issue by andreas-k-beckman** [tryashtar/shulker-preview#11]
First of all, so there are no misunderstanding, I love the datapack :)

But for some testing-purposes I wanted a clean version of the world I'm currently hosting and running this on, and while fiddling around with that I noticed that even if I remove all the datapacks, it still seems to re-create the far-away regions related to this datapack. So, while i did manage to get my testing done this time around, I still thought I should go here and suggest either an actual uninstall function for future versions, or some other help (guide? hints?) with cleaning up a world.

Just in case it's needed for more serious purposes in the future :)

Anyway, keep up the good work!

Best Regards

**Comment by tryashtar** [comment]
Hello, thanks for the comment. You can always just un-forceload the chunk with `/forceload remove 29999977 9832`. Unfortunately, there is no way to delete the region file it generates, nor is there a way to run commands when the datapack is disabled. I'd be a bit uncomfortable introducing a function to do clean up directly, as it would create a confusing additional state of "uninstalled, but still enabled" as a counterpart to "disabled but dormant"

But something in the read-me file could be useful for cases like this

**Comment by andreas-k-beckman** [comment]
Well, even just knowing it's caused by force-loading is a big help :) It's not something I normally play around with, so it's not something I would have thought of :)

So, yes, just a little hint/guide in the readme would probably be enough for the rare cases where someone has my problem :)

**Comment by SirWindfield** [comment]
I'd still like to request the addition of a function called `uninstall` in the root of the project, so `tryashtar.shulker-preview/uninstall` that runs all the stuff listed under the `How do I completely uninstall the pack?` section of the readme. As of now, the function would only remove the scoreboard and unload the forceloaded chunk.

Not a lot of people know about it, but there are some (unofficial) guidelines for datapacks created by the community that focus on user experience improvements and interoperability between different datapacks.

<details><summary>This does contain some stuff that could be added as well to follow those guidelines :)</summary>
The link to the guideline documentation: https://mc-datapacks.github.io/en/tips/holding_right_click_detection.html

Specifically, sections 1.1 for the advancement. This basically creates a common page for datapacks so users see what's installed. Section 1.2 for the above mentioned uninstall function. Section 1.5 to declare the needed AoE clouds as `global.ignore`. That way, other datapacks can filter for those and do not alter them or delete them using the entity selector.

I couldn't find the source code to the datapack on your GitHub. If you are interested, I'd gladly contribute and add those sections to the pack if you're OK with it :smile:
</details>

Thanks for the great pack! You really did pull some advanced stuff off :)

**Comment by tryashtar** [comment]
Thanks for the comment. As I said above, I'm not comfortable adding an uninstall function because it wouldn't uninstall everything. You'd still have to do manual cleanup, including actually disabling the data pack itself. So it would just be kinda misleading.

As for Boomber's lovely "guidelines" (😛), I generally prefer to distance myself. The advancement window looks nice and all, but not when you only have a single one, which is the case a lot of the time. I actually wonder if I could somehow hack it to only show up if it detects that something else is present...
And about the `global.ignore` standard, I'm *definitely* not going to follow that one, hahaha. Luckily, in the case of this pack, it doesn't matter because the only entities created are destroyed later in the same tick, so it's actually impossible for any other pack to select them even by accident.

Anyway, sorry for the probably disappointing reply, hahaha. I have nothing against those standards, in fact it's pretty cool that Boomber (and co?) have managed to cultivate a fairly organized and rational set without being too overbearing (_most_ of the time...) But yeah I generally prefer to opt out of these kinds of things. I kept the "standard" shulker box loot table magic NBT tag, but used undyed instead of yellow to show my rebellion! :P

**Comment by SirWindfield** [comment]
Ah, I didn't know that packs are processed in-order, I always thought that they are actually handled in parallel. Fair enough, you have your reasons and I am not going to question them.
