### ISSUE TITLE
Empty Shulker

### ISSUE THREAD

**Issue by flashpaul** [tryashtar/shulker-preview#18]
I have a problem with empty shulkers. If I fill a shulker and then empty it, the shulker is effectively empty, but when you move the mouse over it as if to preview in the description of the shulker, the contents of the contents remain as if there were still the previous objects in the shulker. If you need further explanations or tests I can do them and attach pictures to better understand.

**Comment by tryashtar** [comment]
How are you emptying it?

**Comment by flashpaul** [comment]
First, I add that I use Paper Spigot which I have not specified before. I don't know if this could affect it. In any case, I manually extract the objects when a shulker is placed on the ground and then when I pick it up it is empty but from the description, it appears as if it still had the previous objects inside

**Comment by tryashtar** [comment]
How strange! Normally when you place a block, all the display information gets wiped. Could you attach a video of this happening? I would love to fix it if I could figure out how to recreate it

**Comment by flashpaul** [comment]
I am forwarding you a sample video: https://drive.google.com/file/d/1L5waeyzkXgIF90y1Jg2FCZa3_45iZSfA/view?usp=sharing

**Comment by flashpaul** [comment]
I also tried to reposition the shulker on the ground which is effectively empty, but breaking it again still remains the purple writing

**Comment by tryashtar** [comment]
Thanks for the video. Would it be possible if I could join the server to investigate a bit?

**Comment by flashpaul** [comment]
What you saw was a local server where I test various plugins. I am sending you a zipped copy of the world with all the plugins present. But I can only do it tomorrow evening. (about 22 hours from now)

**Comment by tryashtar** [comment]
Thanks, that'll work

**Comment by flashpaul** [comment]
I sent you an email with the world link. Thanks for your work!

**Comment by tryashtar** [comment]
Thanks, I was able to figure out the problem with that download!
This is definitely caused by the plugin `TileDataSaver`.

It saves the lore of the item to the placed block. So when the box is emptied and broken, it restores the original lore to the dropped item. It seems to be implemented very strangely, serializing the entire item to bytes and ultimately saving it as a base64 string, instead of just copying the NBT structure. It's hard to say for sure, but that seems to me to be the reason why it changes from the proper image to purple text -- something about text component serialization is lossy.

Empty boxes are not processed by this data pack, for a few reasons. Mostly because I prefer a blank tooltip than an empty inventory tooltip, and also because checking for the presence of an item in the container is a safe and performant filter to process only relevant items. As a result, the lore saved by the plugin persists.

So, as for solutions...
* Easiest one is just to get rid of the `TileDataSaver` plugin.

If you don't want to do that, I was able to modify the data pack to work around the issue, but I would prefer not to include those modifications in the main download because there are minor performance implications. So I have two different modified versions:
* Empty boxes get an empty inventory tooltip
* Empty boxes get a blank tooltip like vanilla

Please let me know which of these you prefer :)

**Comment by tryashtar** [comment]
Alright! Here is the custom version of the data pack -- three files are changed. Do let me know if this works for you :)
[Shulker Preview Data Pack (1.18).zip](https://github.com/tryashtar/shulker-preview/files/8378430/Shulker.Preview.Data.Pack.1.18.zip)

**Comment by flashpaul** [comment]
Can You please update this version to 1.19?

**Comment by tryashtar** [comment]
Hi sorry for the delay, I saw your email. I'll get to this as soon as I get a chance :)

**Comment by flashpaul** [comment]
Ok! Thank you!
