### ISSUE TITLE
Shulker and EC Preview, Badlion

### ISSUE THREAD

**Issue by Damian1357PL** [tryashtar/shulker-preview#19]
Hi, i wanted to use shulker preview on a small 1.18 SMP server. I did as in the Instructions but it doesn't work on the SMP server, nor does it work in SinglePlayer, im using Badlion and Optifine with an extra resourcepack.

![image](https://user-images.githubusercontent.com/38296694/169081902-f91c7a02-407f-4d27-a6c4-3893c0e48b56.png)

I just tried it without Badlion, just with Optifine and it works.

![image](https://user-images.githubusercontent.com/38296694/169082625-d57f0ce9-f7a9-4236-9036-2629df3a702f.png)

Could you add Badlion Support?

**Comment by tryashtar** [comment]
Sorry, I'm not going to look into this.
In general, if a mod breaks the preview, it's the mod's fault for being incompatible with vanilla. In the case of bukkit and optifine, I was willing to patch in fixes because they are ubiquitous, I was able to easily test to find out what was going wrong, and the workarounds were relatively simple.
However I am not willing to install badlion to test it because I do not trust that program with my account information. If you can figure out what exactly is causing the preview to be wrong, feel free to submit a bug report to them or suggest a workaround to me
