### ISSUE TITLE
Dark theme does not show as inventory preview. 

### ISSUE THREAD

**Issue by jagodragon** [tryashtar/shulker-preview#7]
the dark theme only shows the inventory in a black box. this does not show as an inventory screen. (see image) is this a bug in the dark theme?
[link to image](https://i.imgur.com/xCSj35O.png)

**Comment by tryashtar** [comment]
Yeah this is how it's supposed to be. There was a bug one time that caused the inventory to not render, and when I fixed it, someone specifically requested a version that looked that way since they liked it.

If you want a darker UI that matches some other pack, it would be pretty easy to make yourself. The three images you have to modify are the ones in the current dark theme pack, and you can get the original versions from the normal pack
